version: "3.7"

services:
  postgres:
    image: postgres:15-alpine
    networks:
      - postgres
    restart: always
    environment:
      - POSTGRES_DB=db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./conf/db:/docker-entrypoint-initdb.d

volumes:
  postgres-data:

networks:
  postgres:
